# Generated by Django 5.2.1 on 2025-05-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_web_app', '0003_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
